name: "godot gut test"

on: push

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set GODOT_VERSION
        run: echo "GODOT_VERSION=4.4.1" >> $GITHUB_ENV

      - name: Install Godot ${{ env.GODOT_VERSION }}
        uses: pontoco/setup-godot@v1
        with:
          version: ${{ env.GODOT_VERSION }}
          use-dotnet: false
          headless: true

      - name: Preload project resources (generate .import files)
        run: |
          godot --headless --editor --quit --path .

      - name: Run GUT tests
        uses: ceceppa/godot-gut-ci@main
        with:
          godot_version: ${{ env.GODOT_VERSION }}
          gut_params: -gdir=res://tests -gprefix=test_
