name: "godot gut test"
on: push

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker test
        uses: ceceppa/godot-gut-ci@main
        with:
          godot_version: 4.4.1 # uses godot 4.4.1
          gut_params: -gdir=res://tests -gprefix=test_
          project_path: 448test/firstgame
